fix error when autoclose option is nil
This fix following problem.

./lib/hamlit/compiler/tag_compiler.rb:64:in `self_closing?': undefined method `include?' for nil:NilClass (NoMethodError)
Did you mean?  @autoclose